# Generated by Django 2.2 on 2019-05-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('user', models.CharField(default=None, max_length=30)),
                ('image', models.CharField(default=None, max_length=30)),
                ('price', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('pname', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
