# Generated by Django 2.2 on 2019-05-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBVIApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
